export const SET_EMAIL = 'SET_EMAIL';

export const SET_PASSWORD = 'SET_PASSWORD';

export const SAVE_CURRENCIES = 'SAVE_CURRENCIES';

export const SAVE_EXPENSES = 'SAVE_EXPENSES';

export const DELETE_EXPENSES = 'DELETE_EXPENSES';
